sudo: required
dist: trusty

jobs:
  include:
    - stage: test
      language: node_js
      node_js: 8
      os:
        - linux
        # - osx
      install:
        - npm i -g lix haxe-travix
        - lix download
      script:
        - travix node
        - travix neko
        #- travix java
        #- travix interp
        - travix php
        - travix cpp
    
    - stage: deploy
      language: haxe
      haxe: "3.4.7"
      os: linux
      script: skip
      after_success:
        - haxelib install travix
        - haxelib run travix install
        - haxelib run travix release