sudo: required
dist: trusty

language: node_js
node_js: 6

os:
  - linux
      
install:
  - yarn

script:
  - yarn travix node
  - yarn travix neko
  #- yarn travix java
  #- yarn travix interp
  - yarn travix php
